In [1]:
import json
import pandas as pd

file_name = 'luke.json'
raw_Df = pd.read_json(file_name)
raw_Df

,resource_state,athlete,name,distance,moving_time,elapsed_time,total_elevation_gain,type,workout_type,id,...,pr_count,total_photo_count,has_kudoed,average_cadence,average_temp,average_heartrate,max_heartrate,average_watts,kilojoules,device_watts
0,2,"{'id': 15378822, 'resource_state': 1}",Tierra desconocida,4846.8,1289,1298,44.9,Run,0.0,6319270981,...,0,2,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"{'id': 15378822, 'resource_state': 1}",Por la playa con William,8865.5,2806,2912,5.1,Run,0.0,6298283786,...,0,1,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"{'id': 15378822, 'resource_state': 1}",Otra vez con Kalita,5982.9,4400,6925,232.7,Hike,NaN,6290388284,...,0,1,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,"{'id': 15378822, 'resource_state': 1}",Caminando con nov√≠a,6260.2,4267,4902,131.0,Run,0.0,6284808367,...,0,0,False,56.5,25.0,78.9,112.0,NaN,NaN,NaN
4,2,"{'id': 15378822, 'resource_state': 1}",Lunch Run,5126.4,1278,1425,6.0,Run,NaN,6271429904,...,0,0,False,88.8,31.0,151.3,172.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1862,2,"{'id': 15378822, 'resource_state': 1}",2 mile loops with Kalvin&Felix 5/20/16,13035.7,3212,3212,0.0,Run,NaN,591338686,...,0,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1863,2,"{'id': 15378822, 'resource_state': 1}",Up Padua 5/19/16,12874.8,3261,3261,0.0,Run,NaN,591339213,...,0,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1864,2,"{'id': 15378822, 'resource_state': 1}",Mt. Whitney with Kalvin/Felix/Dylan 5/18/16,12874.8,3280,3280,0.0,Run,NaN,592603032,...,0,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1865,2,"{'id': 15378822, 'resource_state': 1}",Baseline East with Felix 5/17/16,12874.8,3180,3180,0.0,Run,NaN,592602673,...,0,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1866,2,"{'id': 15378822, 'resource_state': 1}",First day of CCCP practice 5/16/16,8529.5,2037,2037,0.0,Run,NaN,591339876,...,0,0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cols = ['distance','moving_time','total_elevation_gain','total_photo_count','average_speed','max_speed','achievement_count','kudos_count','average_heartrate','has_title','has_photo']
data = []

f = open(file_name)
activities = json.load(f)
f.close()

for activity in activities:                        
        lst = []
        for col in cols[:-3]: 
            lst.append(activity[col])
        if activity['has_heartrate']:
            lst.append(activity['average_heartrate'])
        else:
            lst.append(-1)
        lst.append(0 if activity['name'] in ['Morning Run', 'Afternoon Run', 'Evening Run'] else 1)
        lst.append(0 if activity['total_photo_count'] == 0 else 1)
        data.append(lst)
        
        
df = pd.DataFrame(data=data, columns=cols)
df

,distance,moving_time,total_elevation_gain,total_photo_count,average_speed,max_speed,achievement_count,kudos_count,average_heartrate,has_title,has_photo
0,4846.8,1289,44.9,2,3.760,6.212,0,22,-1.0,1,1
1,8865.5,2806,5.1,1,3.159,5.958,0,21,-1.0,1,1
2,5982.9,4400,232.7,1,1.360,4.682,0,30,-1.0,1,1
3,6260.2,4267,131.0,0,1.467,2.348,0,13,78.9,1,0
4,5126.4,1278,6.0,0,4.011,6.184,2,7,151.3,1,0
...,...,...,...,...,...,...,...,...,...,...,...
1862,13035.7,3212,0.0,0,4.058,0.000,0,0,-1.0,1,0
1863,12874.8,3261,0.0,0,3.948,0.000,0,0,-1.0,1,0
1864,12874.8,3280,0.0,0,3.925,0.000,0,0,-1.0,1,0
1865,12874.8,3180,0.0,0,4.049,0.000,0,0,-1.0,1,0
1866,8529.5,2037,0.0,0,4.187,0.000,0,0,-1.0,1,0

In [7]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [8]:
from sklearn import linear_model

regr = linear_model.LinearRegression()

# Independent Variables
X = [x for i,x in enumerate(cols) if i!='kudos_count']
X
# Dependent Variable
# Y = df['kudos_count']
# regr.fit(df[])

ModuleNotFoundError: No module named 'sklearn'